### ISSUE TITLE
pas de remontée de données

### ISSUE THREAD

**Issue by LGO44** [kugan49/veolia-custom-component-HACS#6]
Les donnes ne remontent pas dans home assistant

## Configuration:  user: mon adresse mail mot de passe : accès à mon compte
données dispo sur le lien _https://www.service.eau.veolia.fr/home/espace-client/votre-consommation.html?vueConso=historique_
![image](https://user-images.githubusercontent.com/95585425/224176543-baf1866a-24b3-4d46-858b-b71c9ac5ba8d.png)

Add your logs here.

2023-03-09 23:24:35.041 ERROR (SyncWorker_8) [custom_components.veolia] Error 500 fetching data :Pas de consommations retournées par TELEO
2023-03-09 23:24:35.142 ERROR (SyncWorker_8) [custom_components.veolia] Error 500 fetching data :Pas de consommations retournées par TELEO
2023-03-09 23:24:35.150 ERROR (MainThread) [custom_components.veolia.debug] Error in function state: 'historyConsumption'
2023-03-09 23:24:35.153 ERROR (MainThread) [custom_components.veolia.debug] Error in function extra_state_attributes: 'historyConsumption'
2023-03-09 23:24:35.157 ERROR (MainThread) [custom_components.veolia.debug] Error in function state: 'last_index'
2023-03-09 23:24:35.160 ERROR (MainThread) [custom_components.veolia.debug] Error in function extra_state_attributes: 'historyConsumption'
2023-03-09 23:24:35.167 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform veolia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/veolia/sensor.py", line 97, in state
    state = self.coordinator.data[MONTHLY][HISTORY][0][1]
KeyError: 'historyConsumption'
2023-03-09 23:24:35.172 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up veolia platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/veolia/sensor.py", line 97, in state
    state = self.coordinator.data[MONTHLY][HISTORY][0][1]
KeyError: 'historyConsumption'
```

Détail: sur mon compte j'ai 2 compteurs dont un seul me fourni des données .

**Comment by kugan49** [comment]
Bonjour,

Je vois le message `Error 500 fetching data :Pas de consommations retournées par TELEO`
Et le graphe fourni par le site Veolia ne remonte pas de données non plus depuis le 20/02.

J'ai rencontré le même souci pendant 2 semaines.
Le site de Veolia n'est pas très fiable, il faut être patient

**Comment by kugan49** [comment]
Je n'ai pas ce cas de figures, je ne sais donc pas les données qui sont ramenées dans ce cas.
Il me faudrait faire pas mal de tests pour faire un reverse engineering correct.

**Comment by LGO44** [comment]
Biensur si je peux aider, ce sera avec plaisir

**Comment by kugan49** [comment]
Tu peux mettre l'intégration en debug et me transmettre tes logs ?
Je testerais avec ça et on fera quelques essais

**Comment by LGO44** [comment]
Voila les logs:

2023-03-14 08:29:54.418 ERROR (SyncWorker_6) [custom_components.veolia] Error 500 fetching data :Pas de consommations retournées par TELEO
2023-03-14 08:29:54.511 ERROR (SyncWorker_6) [custom_components.veolia] Error 500 fetching data :Pas de consommations retournées par TELEO
2023-03-14 08:29:54.520 ERROR (MainThread) [custom_components.veolia.debug] Error in function state: 'historyConsumption'
2023-03-14 08:29:54.523 ERROR (MainThread) [custom_components.veolia.debug] Error in function extra_state_attributes: 'historyConsumption'
2023-03-14 08:29:54.527 ERROR (MainThread) [custom_components.veolia.debug] Error in function state: 'last_index'
2023-03-14 08:29:54.530 ERROR (MainThread) [custom_components.veolia.debug] Error in function extra_state_attributes: 'historyConsumption'
2023-03-14 08:29:54.537 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform veolia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/veolia/sensor.py", line 97, in state
    state = self.coordinator.data[MONTHLY][HISTORY][0][1]
KeyError: 'historyConsumption'
2023-03-14 08:29:54.543 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up veolia platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/veolia/sensor.py", line 97, in state
    state = self.coordinator.data[MONTHLY][HISTORY][0][1]
KeyError: 'historyConsumption'

**Comment by kugan49** [comment]
Il me les faudrait en mode debug :

Pour activer les logs :
dans le fichier `configuration.yaml` :

```yaml 
logger:
  default: info
  logs:
    custom_components.veolia: debug
```

J'attends ton retour 😄

**Comment by LGO44** [comment]
désolé pour tout a l'heure
Pour info, comme je le disais sur mon compte Veolia j'ai 2 compteurs: 
     _ le premier a Sautron residence principale qui n'a pas de télémesure
     _ le second à Damgan qui a la télémesure cf relevé au dessus 
Ton intégration n'a visiblement pas prévu (encore) la possibilité de plusieurs compteurs

2023-03-14 09:20:34.590 INFO (MainThread) [homeassistant.setup] Setting up veolia
2023-03-14 09:20:34.591 DEBUG (MainThread) [custom_components.veolia.debug] Start function async_setup
2023-03-14 09:20:34.591 DEBUG (MainThread) [custom_components.veolia.debug] End function async_setup
2023-03-14 09:20:34.591 INFO (MainThread) [homeassistant.setup] Setup of domain veolia took 0.0 seconds
2023-03-14 09:20:34.596 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.rpi_power
2023-03-14 09:20:34.604 DEBUG (MainThread) [custom_components.veolia.debug] Start function async_setup_entry
2023-03-14 09:20:34.605 DEBUG (MainThread) [custom_components.veolia.debug] End function async_setup_entry
2023-03-14 09:20:34.812 DEBUG (SyncWorker_7) [custom_components.veolia] resp status=200
2023-03-14 09:20:34.958 DEBUG (SyncWorker_7) [custom_components.veolia] result_getauth={'soap:Envelope': {'@xmlns:soap': 'http://schemas.xmlsoap.org/soap/envelope/', 'soap:Body': {'ns2:getAuthentificationFrontResponse': {'@xmlns:ns2': 'http://ws.icl.veolia.com/', 'return': {'espaceClient': {'cptAuth': 'N', 'cptDLastcon': '2023-03-14T08:29:54+01:00', 'cptEmail': 'le_gallo.christian@orange.fr', 'cptFlgPwdValide': 'O', 'cptNumero': '1001700152', 'cptPwd': '392e2264cea32e857a9da4b8678cc696783ffbd0a559c90efef5cf07', 'cptTel': '0240948062', 'cptTel06': '0642674768', 'flagNewsletter': 'N', 'flagNewsletterLocal': 'N', 'flagSms': 'O'}, 'listContrats': [{'aboId': '0675600140148901', 'aboRefcli': '0675600140148901', 'acpComquar': '21874', 'acpInsee': '44194', 'acpLibperso': '15 RUE DU VIGNEAU', 'acpNumero': '1001573706', 'CLibcom': 'SAUTRON', 'CReg': '06', 'CTraitegn': '756', 'casRdv': '0', 'cliLibcourtciv': 'M', 'cliNom': 'LEGALLO CHRISTIAN', 'clientAbo': {'cliCodepostal': '44880', 'cliCommune': 'SAUTRON', 'cliId': '615253951', 'cliLibcourtciv': 'M', 'cliNom': 'LEGALLO CHRISTIAN', 'cliNomvoie': 'RUE DU VIGNEAU', 'cliNumvoie': '15'}, 'clientPay': {'cliCodepostal': '44880', 'cliCommune': 'SAUTRON', 'cliId': '612616255', 'cliLibcourtciv': 'M', 'cliNom': 'LE GALLO CHRISTIAN', 'cliNomvoie': 'RUE DU VIGNEAU', 'cliNumvoie': '15'}, 'contratMigre': 'false', 'cptNumero': '1001700152', 'hpCodePostal': '44880', 'hpDpt': '44'}, {'aboId': '0631200400002502', 'aboRefcli': '0631200400002502', 'acpComquar': '22735', 'acpInsee': '56052', 'acpLibperso': '3 PASSAGE DU LOCH', 'acpNumero': '1007896770', 'CLibcom': 'DAMGAN', 'CReg': '06', 'CTraitegn': '312', 'casRdv': '0', 'cliLibcourtciv': 'M', 'cliNom': 'LE GALLO CHRISTIAN', 'clientAbo': {'cliCodepostal': '56750', 'cliCommune': 'DAMGAN', 'cliId': '616802436', 'cliLibcourtciv': 'M', 'cliNom': 'LE GALLO CHRISTIAN', 'cliNomvoie': 'PASSAGE DU LOCH', 'cliNumvoie': '3'}, 'clientPay': {'cliCodepostal': '44880', 'cliCommune': 'SAUTRON', 'cliId': '616802437', 'cliLibcourtciv': 'M', 'cliNom': 'LE GALLO CHRISTIAN', 'cliNomvoie': 'RUE DU VIGNEAU', 'cliNumvoie': '15'}, 'contratMigre': 'false', 'cptNumero': '1001700152', 'hpCodePostal': '56750', 'hpDpt': '56'}]}}}}}
2023-03-14 09:20:34.958 DEBUG (SyncWorker_7) [custom_components.veolia] _fetch_data by month ? False
2023-03-14 09:20:34.958 DEBUG (SyncWorker_7) [custom_components.veolia] action=getConsommationJournaliere
2023-03-14 09:20:35.406 DEBUG (SyncWorker_7) [custom_components.veolia] <Response [500]>
2023-03-14 09:20:35.406 DEBUG (SyncWorker_7) [custom_components.veolia] <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>Pas de consommations retournées par TELEO</faultstring><detail><ns1:IclWebServiceException xmlns:ns1="http://ws.icl.veolia.com/"><constraintViolated xmlns:ns2="http://ws.icl.veolia.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><code xmlns:ns2="http://ws.icl.veolia.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/></ns1:IclWebServiceException></detail></soap:Fault></soap:Body></soap:Envelope>
2023-03-14 09:20:35.407 ERROR (SyncWorker_7) [custom_components.veolia] Error 500 fetching data :Pas de consommations retournées par TELEO
2023-03-14 09:20:35.417 DEBUG (SyncWorker_7) [custom_components.veolia] _fetch_data by month ? True
2023-03-14 09:20:35.417 DEBUG (SyncWorker_7) [custom_components.veolia] action=getConsommationMensuelle
2023-03-14 09:20:35.571 DEBUG (SyncWorker_7) [custom_components.veolia] <Response [500]>
2023-03-14 09:20:35.571 DEBUG (SyncWorker_7) [custom_components.veolia] <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>Pas de consommations retournées par TELEO</faultstring><detail><ns1:IclWebServiceException xmlns:ns1="http://ws.icl.veolia.com/"><constraintViolated xmlns:ns2="http://ws.icl.veolia.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><code xmlns:ns2="http://ws.icl.veolia.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/></ns1:IclWebServiceException></detail></soap:Fault></soap:Body></soap:Envelope>
2023-03-14 09:20:35.572 ERROR (SyncWorker_7) [custom_components.veolia] Error 500 fetching data :Pas de consommations retournées par TELEO2023-03-14 09:20:35.597 INFO (MainThread) [homeassistant.setup] Setting up default_config
2023-03-14 09:20:35.601 DEBUG (MainThread) [custom_components.veolia] consumption = {'daily': {}, 'monthly': {}}
2023-03-14 09:20:35.601 DEBUG (MainThread) [custom_components.veolia] Finished fetching veolia data in 0.995 seconds (success: True)
2023-03-14 09:20:35.608 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.veolia
2023-03-14 09:20:35.617 DEBUG (MainThread) [custom_components.veolia.debug] Start function __init__
2023-03-14 09:20:35.618 DEBUG (MainThread) [custom_components.veolia.debug] End function __init__
2023-03-14 09:20:35.618 DEBUG (MainThread) [custom_components.veolia.debug] Start function __init__
2023-03-14 09:20:35.618 DEBUG (MainThread) [custom_components.veolia.debug] End function __init__
2023-03-14 09:20:35.619 DEBUG (MainThread) [custom_components.veolia.debug] Start function __init__
2023-03-14 09:20:35.619 DEBUG (MainThread) [custom_components.veolia.debug] End function __init__
2023-03-14 09:20:35.626 DEBUG (MainThread) [custom_components.veolia.debug] Start function device_info
2023-03-14 09:20:35.626 DEBUG (MainThread) [custom_components.veolia.debug] End function device_info
2023-03-14 09:20:35.627 DEBUG (MainThread) [custom_components.veolia.debug] Start function state
2023-03-14 09:20:35.627 DEBUG (MainThread) [custom_components.veolia.sensor] self.coordinator.data = {}
2023-03-14 09:20:35.627 ERROR (MainThread) [custom_components.veolia.debug] Error in function state: 'historyConsumption'
2023-03-14 09:20:35.632 DEBUG (MainThread) [custom_components.veolia.debug] Start function extra_state_attributes
2023-03-14 09:20:35.632 DEBUG (MainThread) [custom_components.veolia.sensor] Daily : self.coordinator.data = {}
2023-03-14 09:20:35.633 ERROR (MainThread) [custom_components.veolia.debug] Error in function extra_state_attributes: 'historyConsumption'
2023-03-14 09:20:35.634 DEBUG (MainThread) [custom_components.veolia.debug] Start function device_info
2023-03-14 09:20:35.635 DEBUG (MainThread) [custom_components.veolia.debug] End function device_info
2023-03-14 09:20:35.635 DEBUG (MainThread) [custom_components.veolia.sensor] self.coordinator.data = {}
2023-03-14 09:20:35.636 DEBUG (MainThread) [custom_components.veolia.debug] Start function device_info
2023-03-14 09:20:35.636 DEBUG (MainThread) [custom_components.veolia.debug] End function device_info
2023-03-14 09:20:35.636 DEBUG (MainThread) [custom_components.veolia.sensor] state_class = total_increasing
2023-03-14 09:20:35.636 DEBUG (MainThread) [custom_components.veolia.sensor] state_class = total_increasing
2023-03-14 09:20:35.636 DEBUG (MainThread) [custom_components.veolia.debug] Start function state
2023-03-14 09:20:35.637 ERROR (MainThread) [custom_components.veolia.debug] Error in function state: 'last_index'
2023-03-14 09:20:35.638 DEBUG (MainThread) [custom_components.veolia.debug] Start function extra_state_attributes
2023-03-14 09:20:35.638 ERROR (MainThread) [custom_components.veolia.debug] Error in function extra_state_attributes: 'historyConsumption'
2023-03-14 09:20:35.645 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform veolia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/veolia/sensor.py", line 97, in state
    state = self.coordinator.data[MONTHLY][HISTORY][0][1]
KeyError: 'historyConsumption'
2023-03-14 09:20:35.650 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up veolia platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/veolia/sensor.py", line 97, in state
    state = self.coordinator.data[MONTHLY][HISTORY][0][1]
KeyError: 'historyConsumption'

**Comment by kugan49** [comment]
J'ai implémenté une nouvelle fonctionnalité pour renseigner la référence de l'abonnement :
[https://github.com/kugan49/veolia-custom-component-HACS/releases/tag/v1.2.0](url)

**Comment by LGO44** [comment]
Merci beaucoup.
Ca marche
